module Scenes.$0.Global exposing
    ( dataToSDT
    , sdtToData
    , sceneToST
    )

{-| This is the doc for this module

Automatically generated by Messenger.

Don't modify this file.

@docs dataToSDT

@docs sdtToData

@docs sdtToData

-}

import Base exposing (GlobalData, Msg)
import Canvas exposing (Renderable)
import Lib.Scene.Base exposing (..)
import Scenes.$0.Export exposing (..)
import Scenes.SceneSettings exposing (..)


{-| dataToSDT
-}
dataToSDT : Data -> SceneDataTypes
dataToSDT d =
    $0DataT d


{-| sdtToData
-}
sdtToData : SceneDataTypes -> Data
sdtToData dt =
    case dt of
        $0DataT x ->
            x

        _ ->
            nullData


{-| sceneToST
-}
sceneToST : Scene Data -> SceneT
sceneToST sd =
    let
        init : Int -> SceneMsg -> SceneDataTypes
        init t tm =
            dataToSDT (sd.init t tm)

        update : Msg -> GlobalData -> ( SceneDataTypes, Int ) -> ( SceneDataTypes, List SceneOutputMsg, GlobalData )
        update msg gd ( dt, t ) =
            let
                ( sdt, som, newgd ) =
                    sd.update msg gd ( sdtToData dt, t )
            in
            ( dataToSDT sdt, som, newgd )

        view : ( SceneDataTypes, Int ) -> GlobalData -> Renderable
        view ( dt, t ) vp =
            sd.view ( sdtToData dt, t ) vp
    in
    { init = init
    , update = update
    , view = view
    }
